backend:
  name: github
  repo: OlenaKin/Final_project # Replace with your GitHub username and repository name
  branch: new # The branch where the CMS will push content changes
  auth_endpoint: "http://localhost:3000/admin" # The callback URL for OAuth
  login: true # Enables login via GitHub
  api_root: "http://localhost:3000/" # Use the GitHub API endpoint (this should not be localhost)

media_folder: "static/images/uploads" # Where uploaded images are stored
public_folder: "/images/uploads" # Public path to the uploaded images

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/pages" # Location of your pages
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
