backend:
  name: github
  repo: OlenaKin/Final_project # Replace with your GitHub username and repository name
  branch: main # The branch where the CMS will push content changes
  auth_endpoint: "https://finaleprogetto22.netlify.app/admin" # The callback URL for OAuth
  login: true # Enables login via GitHub
  api_root: "https://api.github.com" # GitHub API endpoint

media_folder: "static/images/uploads" # Where uploaded images are stored
public_folder: "/images/uploads" # Public path to the uploaded images

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/pages" # Location of your pages
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
